### ISSUE TITLE
org.bukkit.plugin.InvalidDescriptionException: name '$pluginName' contains invalid characters.

### ISSUE THREAD

**Issue by OverseerK** [noonmaru/kotlin-plugin#3]
Kotlin 플러그인을 빌드해서 1.16.2 Paper에 적용시키면
[16:00:55 ERROR]: Could not load 'plugins\Kotlin.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: name '$pluginName' contains invalid characters.
	at org.bukkit.plugin.PluginDescriptionFile.loadMap(PluginDescriptionFile.java:984) ~[patched_1.16.2.jar:git-Paper-184]
	at org.bukkit.plugin.PluginDescriptionFile.<init>(PluginDescriptionFile.java:252) ~[patched_1.16.2.jar:git-Paper-184]
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:167) ~[patched_1.16.2.jar:git-Paper-184]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:148) ~[patched_1.16.2.jar:git-Paper-184]
	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.loadPlugins(CraftServer.java:387) ~[patched_1.16.2.jar:git-Paper-184]
	at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:208) ~[patched_1.16.2.jar:git-Paper-184]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.2.jar:git-Paper-184]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.2.jar:git-Paper-184]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
plugin.yml에 name, main, version이 읽히지 않아 오류가 생깁니다.
적용시키기 위한 다른 요소가 필요한가요?

**Comment by noonmaru** [comment]
새벽에 올린 버전인가요?

**Comment by OverseerK** [comment]
> 새벽에 올린 버전인가요?

5일 전에 올리신 1.4.10버전 입니다.

**Comment by noonmaru** [comment]
[1.4.10](https://github.com/noonmaru/kotlin-plugin/releases/tag/1.4.10)

다시 업로드 하였습니다만 두번 빌드했는데도 그런 현상은 없네요..
processResources 테스크의 **/*.yml 와일드카드가 경로에 따라 가끔 동작하지 않는것같은데 */*.yml로 변경해서 빌드해보세요

빌드하지 않더라도 jar 파일이 필요하시면 Release에 Binary 파일이 올려져 있습니다.
